In [2]:
import numpy as np
import scipy
import matplotlib as mat
from matplotlib import pyplot as plt
import sklearn
import pandas as pd

In [3]:
from sklearn import model_selection

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [4]:
nameDataset = "iris.txt"
nameFeatures =['len_sepal','width_sepal','len_petal','width_petal','class']
df = pd.read_csv(nameDataset,names=nameFeatures) # returns a dataframe
print(df.head())

   len_sepal  width_sepal  len_petal  width_petal        class
0        5.1          3.5        1.4          0.2  Iris-setosa
1        4.9          3.0        1.4          0.2  Iris-setosa
2        4.7          3.2        1.3          0.2  Iris-setosa
3        4.6          3.1        1.5          0.2  Iris-setosa
4        5.0          3.6        1.4          0.2  Iris-setosa


In [5]:
print(df.shape)

(150, 5)


In [6]:
print(df.describe())

        len_sepal  width_sepal   len_petal  width_petal
count  150.000000   150.000000  150.000000   150.000000
mean     5.843333     3.054000    3.758667     1.198667
std      0.828066     0.433594    1.764420     0.763161
min      4.300000     2.000000    1.000000     0.100000
25%      5.100000     2.800000    1.600000     0.300000
50%      5.800000     3.000000    4.350000     1.300000
75%      6.400000     3.300000    5.100000     1.800000
max      7.900000     4.400000    6.900000     2.500000


In [7]:
df.groupby('class').size()

class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64

In [8]:
data=df.values

In [9]:
X=data[:,0:-1]
Y=data[:,-1]
print(X[0:9])
print(Y[0:9])

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [10]:
Val_size=0.30
random_seed=3
X_train,X_test,Y_train,Y_test=model_selection.train_test_split(X,Y,test_size = Val_size,random_state=random_seed)

In [12]:
deciTree = DecisionTreeClassifier()
deciTree.fit(X_train, Y_train)
predictions = deciTree.predict(X_test)
print("Accuracy on the Test Data ")
print(accuracy_score(Y_test, predictions))
print()
print()
print("Clasification Report on the Test Data")
print(classification_report(Y_test, predictions))

Accuracy on the Test Data 
0.977777777778


Clasification Report on the Test Data
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        17
Iris-versicolor       1.00      0.93      0.96        14
 Iris-virginica       0.93      1.00      0.97        14

    avg / total       0.98      0.98      0.98        45



In [13]:
eval = 'accuracy'
seed = 4
model = DecisionTreeClassifier()
kfold = model_selection.KFold(n_splits=5, shuffle=True, random_state=seed) #shuffle the data 
results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring=eval)
print(results)
metricResult= results.mean()
print(metricResult)

[ 0.85714286  0.95238095  0.85714286  0.95238095  0.9047619 ]
0.904761904762
